   //FSM Methods Required for class  CDPLAYER  generated by FSM_CodeBuilder 19/10/2020 16:24:03

      // Implementation of State Begin



      // Implementation of State Playing



      // Implementation of State Paused



      // Implementation of State Stopped



